import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

export type Profile = 'Core' | 'Standard' | 'Complete'

export interface Requirement {
  id: string
  profile: Profile
  level: 'MUST' | 'MUST NOT' | 'SHOULD' | 'SHOULD NOT' | 'MAY'
  area: string
  evidence: 'behavior' | 'inspection'
  statement: string
}

export interface Catalog {
  protocol: string
  protocolVersion: string
  catalogRevision: number
  normativeSource: string
  sourceSections: Record<string, string>
  profiles: Record<Profile, { inherits: Profile | null, description: string }>
  resultSemantics: Record<string, string>
  requirements: Requirement[]
  extensions: Array<{ id: string, name: string, requires: string[] }>
}

export function validateCatalog(catalog: Catalog): string[] {
  const errors: string[] = []
  const seen = new Set<string>()
  const prefix: Record<Profile, string> = { Core: 'CORE-', Standard: 'STD-', Complete: 'COMP-' }

  if (catalog.profiles.Core.inherits !== null) errors.push('Core must not inherit another profile')
  if (catalog.profiles.Standard.inherits !== 'Core') errors.push('Standard must inherit Core')
  if (catalog.profiles.Complete.inherits !== 'Standard') errors.push('Complete must inherit Standard')

  for (const requirement of catalog.requirements) {
    if (!/^(CORE|STD|COMP)-[A-Z]+-[0-9]{2}$/.test(requirement.id)) errors.push(`${requirement.id}: invalid requirement ID`)
    if (seen.has(requirement.id)) errors.push(`${requirement.id}: duplicate requirement ID`)
    seen.add(requirement.id)
    if (!requirement.id.startsWith(prefix[requirement.profile])) errors.push(`${requirement.id}: does not match ${requirement.profile} profile`)
    if (!catalog.sourceSections[requirement.area]) errors.push(`${requirement.id}: area '${requirement.area}' has no normative source section`)
    if (requirement.statement.length < 10) errors.push(`${requirement.id}: statement is too short`)
  }

  for (const result of ['pass', 'fail', 'skipped', 'unsupported', 'exception', 'experimental']) {
    if (!catalog.resultSemantics[result]) errors.push(`missing result semantic '${result}'`)
  }

  for (const extension of catalog.extensions) {
    if (!/^EXT-[A-Z0-9]+-[0-9]{2}$/.test(extension.id)) errors.push(`${extension.id}: invalid extension ID`)
    if (seen.has(extension.id)) errors.push(`${extension.id}: duplicate ID`)
    seen.add(extension.id)
    if (extension.requires.length === 0) errors.push(`${extension.id}: must declare evidence requirements`)
  }

  return errors
}

export function renderCatalog(catalog: Catalog): string {
  const rows = catalog.requirements.map((requirement) => {
    const source = catalog.sourceSections[requirement.area]
    return `| \`${requirement.id}\` | ${requirement.profile} | ${requirement.level} | [${requirement.area}](${source}) | ${requirement.evidence} | ${requirement.statement} |`
  }).join('\n')
  const extensions = catalog.extensions.map(extension => `| \`${extension.id}\` | ${extension.name} | ${extension.requires.join('; ')} |`).join('\n')
  const counts = (['Core', 'Standard', 'Complete'] as Profile[])
    .map(profile => `${profile}: ${catalog.requirements.filter(requirement => requirement.profile === profile).length}`)
    .join(' · ')

  return `<!-- Generated by scripts/protocol.ts. Do not edit by hand. -->
# Stacks Protocol ${catalog.protocolVersion} requirement catalog

Catalog revision ${catalog.catalogRevision}. ${counts}.

Profile inheritance is \`Core ← Standard ← Complete\`. Security requirements are
part of Core. Only \`pass\` satisfies a required profile entry; failed, skipped,
unsupported, exception, and experimental results do not.

| ID | Profile | Level | Normative source | Evidence | Requirement |
| --- | --- | --- | --- | --- | --- |
${rows}

## Independent extension badges

Extensions do not change the Core, Standard, or Complete result.

| ID | Extension | Required evidence |
| --- | --- | --- |
${extensions}
`
}

export function loadCatalog(root: string): Catalog {
  return JSON.parse(readFileSync(resolve(root, 'protocol/1.0-draft/catalog.json'), 'utf8')) as Catalog
}

if (import.meta.main) {
  const root = resolve(import.meta.dir, '..')
  const catalog = loadCatalog(root)
  const errors = validateCatalog(catalog)
  if (errors.length > 0) {
    for (const error of errors) console.error(`error: ${error}`)
    process.exit(1)
  }

  const outputPath = resolve(root, 'protocol/1.0-draft/REQUIREMENTS.md')
  const rendered = renderCatalog(catalog)
  if (process.argv.includes('--write')) {
    writeFileSync(outputPath, rendered)
    console.log(`Wrote ${outputPath}`)
  }
  else if (process.argv.includes('--check')) {
    const current = readFileSync(outputPath, 'utf8')
    if (current !== rendered) {
      console.error('error: protocol/1.0-draft/REQUIREMENTS.md is stale; run bun run generate')
      process.exit(1)
    }
    console.log(`Protocol catalog checks passed (${catalog.requirements.length} requirements, ${catalog.extensions.length} extensions)`)
  }
}
